# version: '3'
# services:
#   web:    # can be anything (e.g. react-app)
#     build:
#       context: .    # specify where we want docker to pull the files from
#       dockerfile: Dockerfile.dev  # overriding dockerfile selection
#     ports:
#       - '3000:3000'
#     volumes:
#       - /app/node_modules # do not try to map a folder up against node_modules inside the container
#       - .:/app            # . indicates current working directory and is outside the container, which (.) is mapped to /app inside the container
#   tests:
#     stdin_open: true
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     volumes:
#       - /app/node_modules
#       - .:/app
#     command: ['npm', 'run', 'test']
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'